#!/bin/bash
echo "Executing celery multi start worker1 -A djYlplines"
cd $OPENSHIFT_REPO_DIR
cd wsgi
cd djYlplines
rm worker1.pid
celery multi stop worker1
celery multi start worker1 -A djYlplines -c 1