#!/usr/bin/env python
"""
ylplines - Clarity for Yelp
Copyright (C) 2016  Jeff Lee

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import newrelic.agent
newrelic.agent.initialize()

import os
import sys
from distutils.sysconfig import get_python_lib
import django.core.wsgi

os.environ['DJANGO_SETTINGS_MODULE'] = 'djYlplines.settings'
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'djYlplines'))
os.environ['PYTHON_EGG_CACHE'] = get_python_lib()
application = django.core.wsgi.get_wsgi_application()
